# Generated by Django 4.0.6 on 2022-08-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
