# Generated by Django 4.0.6 on 2022-08-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
